Portfolio setup mobile version
AleMdta/portfolio-mobile-version pull request #1
Opened 2023-06-08 21:38 UTC by AleMdta

In this milestone:
-It was created a skeleton using HTML of the portfolio (toolbar and headline).
-After that, it was styled using CSS, specifically with Flexbox and basic commands to align the content.
-Then the readme file was modified with the information needed.
-Finally, linters configurations were done.

P.S. I will appreciate all the feedback you can give me to make my work better. 
Thanks in advance.

2023-06-08 21:47 UTC, shahadat3669 requested changes
Hi @AleMdta , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<img src="https://media1.giphy.com/media/jmqAUNFXAElgafPK0g/giphy.gif"/>

## Invalid Code Review Request

- [ ] You have submitted a project that does not follow the [GitHub Flows](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md). According to GitHub Flows, the base branch name should be "main." However, in your project, the base branch name is currently "master." Please rename or change your base branch name to "main" to align with the recommended practice. You can refer to this [official document](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) for further assistance on renaming a branch. Keep up the good work! 👍

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-08 23:02 UTC, AdnanOlarmmi requested changes
Hi @AleMdta, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Nice design.
- Used flexbox properly.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 23:02 UTC, AdnanOlarmmi commented on index.html
> +    </nav>
- [ ] Kindly wrap this section with the `header` tag, as this is good for semantic and user experience reasons, and it also enhance SEO.

2023-06-08 23:02 UTC, AdnanOlarmmi commented on index.html
> +            <footer class="social-media">
- [ ] Following the semantic HTML principles, I don't think it is time for you to start using the `footer` tag, kindly change this tag, for semantic and user experience purposes.

2023-06-08 23:02 UTC, AdnanOlarmmi commented on index.html
> +            </section>
- [ ] Kindly use a `button` tag or an `a` tag for buttons, it shouldn't be a section tag. 😄 This is good for user experience and semantic principle.

2023-06-08 23:02 UTC, AdnanOlarmmi commented on style.css
> +  display: flex;
- [ ] It is noticed that `display: flex` property is repeated multiple times, Kindly let us stick to the DRY principle by not repeating a property more than it should 🙂. This can be done by having a class called `.flex-row` or `.flex-column` and assigning it wherever possible as a class name in your `html` markup code.
```
.flex-row {
  display: flex;
}

.flex-column {
  display: flex;
  flex-direction: column;
}
```

```
<ul class="flex-row">
    <li>
        <a href="https://twitter.com/AleMdta"><img src="./images/twitter.svg" alt=""></a>
    </li>
  </li>
  <li>
      <a href="#"><img src="./images/medium.svg" alt=""></a>
  </li>
  <li>
      <a href="https://github.com/AleMdta"><img src="./images/github.svg" alt=""></a>
  </li>
    <li>
        <a href="#"><img src="./images/angellist.svg" alt=""></a>
    </li>
</ul>
```
- And kindly attend to any repetitions in your code 🙂.
- Kindly note that DRY is a requirement, but since the other reviewers have been overlooking it, I've decided to mark it as optional. 😉

2023-06-08 23:02 UTC, AdnanOlarmmi commented on style.css
> +  padding-left: 100px;
- [ ] I studied your reason for doing this like this, by using justify-content: left; and padding-left 100px which isn't responsive.

<img width="155" alt="image" src="https://github.com/AleMdta/portfolio-mobile-version/assets/41163571/41ca2510-56b4-4780-8f19-48f6b5294837">

- After adding border to the container, removing the margin and centering the element I realized there is some left margin outside the container
<img width="175" alt="image" src="https://github.com/AleMdta/portfolio-mobile-version/assets/41163571/5ac5002a-cbd6-4654-bbe2-b35386204812">

On default the browser adds default margin and border to elements and containers, to get rid of this action you'll have to reset default styles, adding this to your styles.
```
*,
*::before,
*::after {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
```
This resets the styles
<img width="212" alt="image" src="https://github.com/AleMdta/portfolio-mobile-version/assets/41163571/bc4166b8-8f8c-4aa1-b01d-16504e2603a6">
 
You can see the default margin has been removed.

- [ ] Lastly, you should align the item properly horizontally by shifting the M icon a bit, and probably making it bigger, try thing and tweak things like a developer will do, have a nice time 👋

2023-06-08 23:43 UTC, AleMdta commented
These were some changes I made to my project.

2023-06-09 00:05 UTC, brainconnect93 requested changes
### Hi @AleMdta, 👋 

# STATUS: Changes Required :recycle:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight :1st_place_medal: 

- Descriptive Pull Request title and summary. ✔️  
- Portfolio: setup and mobile first ✔️  
- Follow the Figma Design Template ✔️  
- Touchable mobile screen size of `375px` ✔️  
- Good use of Github flow ✔️  

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 00:05 UTC, brainconnect93 commented on index.html
> +            </section>
- [ ] As suggested by the previous reviewer,  kindly make this a `button` or an anchor  `a` tag for semantic reason an it should not be wrapped inside of a section tag :+1:

2023-06-09 00:05 UTC, brainconnect93 commented on index.html
> +        </div>
- [OPTIONAL]
I would kindly suggest you make the container of the part a `section` tag instead of using a `div` tag.

- The container of the section is a `section` tag.
       - It represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info.

2023-06-09 00:05 UTC, brainconnect93 commented on style.css
> +  display: flex;
- [ ] I would kindly suggest you work on the suggestion given by the previous reviewer concerning repetition of `display: flex;` multiple times in your CSS as this is against the DRY method of coding practices.

Kindly check the example he gave and try to come up with something fantastic

2023-06-09 01:15 UTC, AleMdta commented
Hello.
The previous reviewers told me to make classes for flex, but as I not only make changes in the position but also in the padding, margin, etc. I consider that I would not be able to call my sections with flex-row and that.
I tried not to repeat so much flex display.
I don't know what to do anymore. :(

2023-06-09 01:25 UTC, mahbubul14 approved these changes
# Project Approved :trophy: :tada: 

Hi @AleMdta, 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linter error.
:heavy_check_mark: Descriptive readme file.
:heavy_check_mark: Clean code.

### Optional suggestions :arrow_down_small: 

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

* N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-06-09 01:27 UTC, merged